services:
  - type: web
    name: code-bunny-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: code-bunny-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://rabbitai-3.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0